name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
#      - name: phpcs
#        uses: geneccx/phpcs-reviewdog-action@v0.1-alpha
#        with:
#          github_token: ${{ secrets.github_token }}
#          phpcs_args: "--standard=PSR12 ./src"
#          reporter: github-pr-review # Default is github-pr-check
      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
      - name: Setup phpcs
        run: |
          curl -L https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o $HOME/bin/phpcs
          chmod +x $HOME/bin/phpcs
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          checkstyle=$HOME/report_checkstyle.xml
          exit_code=$HOME/exit_code
          phpcs --standard=PSR12 --report-checkstyle=${checkstyle} \
            $(git diff --diff-filter=AM --name-only origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} | grep "\.php$") \
            | 2>&1 > ${exit_code}
          cat ${checkstyle} | reviewdog -f=checkstyle -diff="git diff master" -reporter="github-pr-review"
          cat ${exit_code}
      - name: Run phpcs
        if: always()
        run: |
          phpcs --standard=PSR12 --report=summary \
            $(git diff --diff-filter=AM --name-only origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} | grep "\.php$")
