name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
#      - name: phpcs
#        uses: geneccx/phpcs-reviewdog-action@v0.1-alpha
#        with:
#          github_token: ${{ secrets.github_token }}
#          phpcs_args: "--standard=PSR12 ./src"
#          reporter: github-pr-review # Default is github-pr-check
      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
      - name: Setup phpcs
        run: |
          curl -L https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o $HOME/bin/phpcs
          chmod +x $HOME/bin/phpcs
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          checkstyle=$HOME/report_checkstyle.xml
          phpcs --standard=PSR12 --report-checkstyle=${checkstyle} \
            $(git diff --diff-filter=AM --name-only origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} | grep "\.php$")
          cat ${checkstyle} | reviewdog -f=checkstyle -diff="git diff master" -reporter="github-pr-review"
      - name: Run phpcs
        if: always()
        run: |
          phpcs --standard=PSR12 --report=summary \
            $(git diff --diff-filter=AM --name-only origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} | grep "\.php$") \
#     - name: Run reviewdog
#       env:
#         REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       run: |
#         reviewdog -reporter=github-pr-check -runners=golint,govet
#         # or
#         reviewdog -reporter=github-pr-review -runners=golint,govet
#       name: 'Run phpcs with reviewdog'
#       description: 'Run phpcs with reviewdog on pull requests to improve code review experience.'
#       author: 'Gene Chen (geneccx)'
#       inputs:
#         github_token:
#           description: 'GITHUB_TOKEN.'
#           required: true
#         reporter:
#           description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
#           default: 'github-pr-check'
#         phpcs_args:
#           description: 'Arguments to pass to phpcs'
#           default: '.'
#       runs:
#         using: 'docker'
#         image: 'Dockerfile'
#         args:
#           - ${{ inputs.github_token }}
#           - ${{ inputs.reporter }}
#           - ${{ inputs.phpcs_args }}
#       branding:
#         icon: 'edit'
#         color: 'gray-dark'
